"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](fg:surface2)\
[](fg:surface1)\
$os\
[](bg:peach fg:surface1)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c$rust$golang$nodejs$php$java$kotlin$haskell$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[](fg:lavender)\
$line_break\
[╰─](fg:surface2)\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:surface1 fg:text"

[os.symbols]
Arch = "   "
Linux = " 󰌽  "

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 0

[directory.substitutions]
"~" = " "

[git_branch]
symbol = " "
style = "bg:yellow fg:crust"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:yellow fg:crust"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[rust]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[golang]
symbol = "󰟓 "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[php]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[kotlin]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[haskell]
symbol = " "
style = "bg:green"
format = '[[ $symbol](fg:crust bg:green)]($style)'

[python]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[conda]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $environment) ](fg:crust bg:sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'

[palettes.catppuccin_mocha]
red = "#ff5f5f"
peach = "#ed8796"
yellow = "#eed49f"
green = "#a6da95"
sapphire = "#7dc4e4"
lavender = "#b4befe"
crust = "#11111b"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
text = "#1793d1"
